package edu.everton.dia95;
/*
 * This Java source file was generated by the Gradle 'init' task.
 * Esse codigo é parte faz parte de um exercício sobre GradleW,
 * de como seria entrar em um projeto de uma equipe com um GradleW já configurado!
 * 
 */

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
